DROP DATABASE IF EXISTS sugarparty;

CREATE DATABASE sugarparty;

USE sugarparty;

CREATE TABLE categories(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT
);

CREATE TABLE products(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  category_id INT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(15,2) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT 0,
  FOREIGN KEY(category_id) REFERENCES categories(id)
);

CREATE TABLE orders(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  message TEXT,
  status TINYINT UNSIGNED NOT NULL DEFAULT 0,
  price DECIMAL(15,2) NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE order_items(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_id INT UNSIGNED NOT NULL,
  product_id INT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  price DECIMAL(15,2) NOT NULL,
  FOREIGN KEY(order_id) REFERENCES orders(id),
  FOREIGN KEY(product_id) REFERENCES products(id)
);
